### ISSUE TITLE
How to reflash the Mini?

### ISSUE THREAD

**Issue by UweBonnes** [RadioOperator/CMSIS-DAP_for_STLINK-V3MINI#2]
Please describe how to reflash the Mini!

**Comment by RadioOperator** [comment]
@UweBonnes  Hi, reflash the F723 internal flash ROM:
1. prepare another JLINK or STLINK(v2 ok) tools, connect it to the CN3 on the Mini board (4pins).
2. run a Windows programmer software: JFlashLite.exe for JLINK, or ST-LINK utility for STLINK.
3. flash the HEX / BIN code into the F723. start address is 0x08000000.

if you are using Keil, need one of JLINK / STLINK / CMSIS-DAP tool also, connect F723 in SWD mode (CN3), open my source code project, rebuild and load it.

**Comment by UweBonnes** [comment]
I do not find a pinout for CN3. I can only decipher GND as the second pin from left when "CN3" is  readable..

**Comment by RadioOperator** [comment]
@UweBonnes 
![CN3-SWD-Port](https://user-images.githubusercontent.com/27762920/86225610-0d070b80-bbbd-11ea-9672-7763ca4f9495.JPG)

**Comment by UweBonnes** [comment]
Thanks.

I found  this and more information as CMSIS-DAP_for_STLINK-V3MINI/STLINK-V3MINI/Sch/STLINK-V3MINI_GPIOs.JPG
