### ISSUE TITLE
Please upload the pinout in searchable format

### ISSUE THREAD

**Issue by martonmiklos** [RadioOperator/CMSIS-DAP_for_STLINK-V3MINI#3]
Hello @RadioOperator 

May I ask you to upload the source of this image in any textual format:
https://github.com/RadioOperator/CMSIS-DAP_for_STLINK-V3MINI/blob/master/STLINK-V3MINI/Sch/STLINK-V3MINI_GPIOs.JPG

Many thanks in advance!

**Comment by RadioOperator** [comment]
@martonmiklos Hi,
attached here.
[STLINK-V3MINI_Pin_Assignments.xlsx](https://github.com/RadioOperator/CMSIS-DAP_for_STLINK-V3MINI/files/4945922/STLINK-V3MINI_Pin_Assignments.xlsx)
I'll commit it to file group later.

**Comment by martonmiklos** [comment]
Many thanks!

**Comment by RadioOperator** [comment]
@martonmiklos Hi, the GPIOs docs updated, pls note.
