### ISSUE TITLE
Possible missmatch in GPIOs.JPG

### ISSUE THREAD

**Issue by UweBonnes** [RadioOperator/CMSIS-DAP_for_STLINK-V3MINI#4]
Hello,

thank you for the STLINK-V3 pin description at 
https://github.com/RadioOperator/CMSIS-DAP_for_STLINK-V3MINI/blob/master/STLINK-V3MINI/Sch/STLINK-V3MINI_GPIOs.JPG
However for the 32pin edge connector Pin 7 I see a missmatch. UM2502 labels it as "Bridge SPI CLK" while the JPG says "PB5/PC7". However neither of PB5/PC7 has the SPI2_SCK functionality. Maybe it is even connected to a third pin or something is wrong.

Bye

**Comment by RadioOperator** [comment]
@UweBonnes Hi, 
Thanks for pointing out the error.

Re-checked, PA9 is Pin7 with SPI2_SCK, 
and PB5/PC7/PD2 on Pin6. Docs updated.

**Comment by UweBonnes** [comment]
Thanks
