### ISSUE TITLE
Use micropython bootloader

### ISSUE THREAD

**Issue by koendv** [RadioOperator/CMSIS-DAP_for_STLINK-V3MINI#5]
RadioOperator,

I found your documentation about the stlink v4 mini very interesting. But instead of writing my own bootloader I used the micropython bootloader. This way one can advance swiftly. I provide a link, in case you could use the source in your project. Could you give me your opinion?

https://github.com/koendv/micropython

**Comment by RadioOperator** [comment]
@koendv  Hi,
Thanks, I'll check it all later.

Btw, my STLINK-V3MINI pin assignments updated, please correct yours:

32pin edge connector: Pin-6 and Pin-7 changed.
JTAG connector:  Pin-8 changed.

Refer to:
https://github.com/RadioOperator/CMSIS-DAP_for_STLINK-V3MINI/blob/master/STLINK-V3MINI/Sch/STLINK-V3MINI_Pin_Assignments_v3.xlsx

**Comment by koendv** [comment]
The new pinout is interesting.

At the moment SWD speed depends upon processor speed. It would be nice to be able to set SWD speed in an accurate way, independent of processor speed.

In the stlink v3 mini, SWDIO is SPI5_MOSI and SPI5_MISO connected together, and SWCLK is SPI5_CLK. Using SPI5 for SWD seems logical. What do you think?

**Comment by RadioOperator** [comment]
@koendv  very good findings. Stlink-v3 claims SWD speed up to 24 MHz, that is the reason, using SPI5. 
Then we could try SPI5 for SWD, make out 24MHz DAP and Black-Magic-Probe.
(the pin assignments file just updated for some details (v2 to v3), pls check).

**Comment by koendv** [comment]
Too much praise. Perhaps we could work together to write software? Two know more than one, and we are sure to encounter unforeseen problems before we solve this riddle.

I was wondering: is it possible to read the configuration registers of spi5? Or the configuration registers of the jtag connector pins?

**Comment by RadioOperator** [comment]
@koendv  Hi, to read the configuration registers, I did not try on this. I think something same as dumping the bootloader.

**Comment by UweBonnes** [comment]
@koendv: Do you have BMP running somehow on the F7?

**Comment by koendv** [comment]
On Fri, 14 Aug 2020 06:14:07 -0700
UweBonnes <notifications@github.com> wrote:

> @koendv: Do you have BMP running somehow on the F7?
> 

Yes.

**Comment by UweBonnes** [comment]
-vvv please!

**Comment by koendv** [comment]
I've compiled binaries for you, so you can test: https://github.com/koendv/micropython/releases/tag/v1.12-bmp-04

**Comment by koendv** [comment]
radiooperator: If a dentist takes an x-ray of the stlink v3 mini, do you think we could see all connections in the pcb?

**Comment by RadioOperator** [comment]
> radiooperator: If a dentist takes an x-ray of the stlink v3 mini, do you think we could see all connections in the pcb?

Hi, not easy. I used a simple software to initial/read all GPIO pins, and got the table.
