### ISSUE TITLE
Provide builds that can be uploaded with the original ST bootloader

### ISSUE THREAD

**Issue by UweBonnes** [RadioOperator/CMSIS-DAP_for_STLINK-V3MINI#6]

**Comment by RadioOperator** [comment]
Hi, @UweBonnes,
Everything is ready to use in repo:
https://github.com/RadioOperator/Yet_Another_Bootloader
https://github.com/RadioOperator/Yet_Another_Bootloader/tree/master/STLINKv3_YAB

First, install the coexist version YAB (already built).
Then, into YAB mode, and Drag&Drop the pre-built DAP code (in APP sample folders, HID or WinUSB mode) to APP_HERE drive.
Please refer to the Readme.txt file for details.
