### ISSUE TITLE
PA7 is SWD direction signal

### ISSUE THREAD

**Issue by UweBonnes** [RadioOperator/CMSIS-DAP_for_STLINK-V3MINI#7]
Hello,

PA7 is the SWD direction signal. High mean SWD write. 
![stlinkv3_pa7](https://user-images.githubusercontent.com/1142704/98827913-b09fdc80-2437-11eb-88f1-516349f3d40b.png)

Please consider to add to the pinout.

Bye

**Comment by RadioOperator** [comment]
Hi, UweBonnes, Thanks. 
In STLINK-V3MINI original factory configs, PA7 named T_SW_DIR, but not used in User Manual(STDC14 pin-2, reserved).
CMSIS-DAP source code, not use T_SW_DIR control signal.
It is important, or not?

My latest version Pinout file, already added in Table, not highlight it. I do not know what function is.

**Comment by UweBonnes** [comment]
The pin table is a good reference and I would appreciate if it is rather verbose.
