### ISSUE TITLE
Something simple? Udefined symbol RCC_GetUSARTClockFreq

### ISSUE THREAD

**Issue by RandoSY** [RadioOperator/CMSIS-DAP_for_STLINK-V3MINI#8]
Howdy!

Thanks for this great posting, much to learn here...

As a first step I caught just one error on compile with Keil 5.25.2.0:

.\Listings\STM32F723_YAB.axf: Error: L6218E: Undefined symbol LL_RCC_GetUSARTClockFreq (referred from usart_stm32f7xx.o)

Am I missing an include, or something simple?  (compiler is set at c99)

Thanks

**Comment by RadioOperator** [comment]
Hi, maybe your Keil not install the latest STM32F7xx_DFP pack. Keil will find the function automatically, no included needed.

The function LL_RCC_GetUSARTClockFreq in file stm32fxx_ll_rcc.c, already added in project, the source in Keil system, you could try to search LL_RCC_GetUSARTClockFreq globally.

![image](https://user-images.githubusercontent.com/27762920/126051987-e60ca581-9053-4556-bd87-0c2f739f01ef.png)

**Comment by RandoSY** [comment]
I did a global search and found as expected ... am I missing a compile time switch that forces the appropriate define? 
My packs are completely updated. Sorry to be dense on this :)

![Define failure for RCC](https://user-images.githubusercontent.com/609947/126068867-38ed0b8e-ee79-476c-9b8d-d1b9aaaec0a6.JPG)

**Comment by RandoSY** [comment]
I did try the USE_HAL_DRIVER, and USE_FULL_LL_DRIVER, switches on the compiler command line, no change... this was posted on the comments to the latest STM32X7 pack.

**Comment by RadioOperator** [comment]
Hi, before you try to modify my code, you'd better to use all my settings to compile first.

the following pic maybe help, the project files linked to STM32F7xx based Keil-ARM RTE environment, not others such as STM32Cube, so no USE_HAL_DRIVER or USE_FULL_LL_DRIVER pre-define.
![Capture](https://user-images.githubusercontent.com/27762920/126070343-9f12ac3e-845c-499a-bed1-7a52d09b9f2b.PNG)

**Comment by RadioOperator** [comment]
![Capture](https://user-images.githubusercontent.com/27762920/126070930-5082c597-7a2b-430b-8da2-a94b175630e2.PNG)

**Comment by RandoSY** [comment]
OK, thanks for your excellent guidance, I am in line with your setup, I think. I'm still getting the error aforementioned. 

Is this warning relevant?

[C:/Keil_v5/ARM/PACK/Keil/STM32F7xx_DFP/2.14.0/CMSIS/Driver/USART_STM32F7xx.c(1757): warning: implicit declaration of function 'LL_RCC_GetUSARTClockFreq' is invalid in C99 [-Wimplicit-function-declaration]
    freq = LL_RCC_GetUSARTClockFreq (LL_RCC_USART1_CLKSOURCE);](url)

Note, "invalid in C99" message.

**Comment by RandoSY** [comment]
There are slight differences on my setup, let me try and resolve completely.  Thanks for your help!
